---
title: "Brazilian Aeronautics Accidents"
description: |
  Statistical computation and visualization (MATH-517)
date: December 24, 2021
author:
- name: "Zineb AGNAOU"  
  url: https://github.com/ZinebAg
- name: "Fahim BECK"
  url: https://github.com/FahimBeck
- name: "Yiren CAO"
  url: https://github.com/yirencao
- name: "Matias JANVIN"
  url: https://github.com/matiasjanvin
- name: "Salima JAOUA"
  url: https://github.com/salimajaoua
- name: "Seorim PARK"
  url: https://github.com/seorimpark
output: distill::distill_article
bibliography: bibliography.bib
nocite: '@*'
---

<div style="text-align: justify">
<div style="text-justify: inter-word">

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(knitr.duplicate.label = "allow")
```

## Introduction

### Research questions


### Approaches


## Sources of information / datasets



````{r packages, include=FALSE}
library(ggplot2)
library(tidyr)
library(dplyr)
library(corrplot)
````

```{r,include=FALSE}
tex2markdown <- function(texstring) {
  writeLines(text = texstring,
             con = myfile <- tempfile(fileext = ".tex"))
  texfile <- pandoc(input = myfile, format = "html")
  cat(readLines(texfile), sep = "\n")
  unlink(c(myfile, texfile))}
```

## First section 

```{r, echo=FALSE}

library(nominatim)
library(stringi)

names = c("Neuchâtel", "EPFL")
names_ascii = stri_trans_general(names, id = "Latin-ASCII")
places = osm_search(names_ascii, key = "BEPERuyOgxAQ5JX0H7oOHfAFmyb4tBnx")
table = cbind(names, places[, c("lon", "lat", "display_name")])

library(leaflet)

leaflet(data = table) %>% addTiles() %>%
  addMarkers(~lon, ~lat, popup = ~as.character(display_name), label = ~as.character(names))

```


## Second section 


## Conclusion


## Future improvements


<div id="refs"></div>

