---
title: "TimeAnalysis"
output: html_document
---


```{r, include=FALSE}
library(readr)
library(lubridate)
library(ggplot2)
library(dplyr)
library(tidyr)
```

```{r, include=FALSE}
data <- read_csv("../Data/aircrafts_occurrences_merged.csv")
data$occuranceWeek <- as.Date(data$occurrence_day)
data$occuranceWeek <-wday(data$occuranceWeek, label=TRUE)

data$publicationWeek <- as.Date(data$publication_day)
data$publicationWeek <-wday(data$publicationWeek, label=TRUE)
# occurrence_id,,occurrence_day,publication_day, invistigation status
```

```{r, include=FALSE}
data$occuranceWeek <- as.Date(data$occurrence_day)
```

```{r,echo=FALSE}
hist(strptime(data$time, format="%H:%M:%S"),main="Distribution of Accidents throughout the hours of the day",xlab="Hours of the day",breaks="hours")
```

```{r, echo=FALSE}
hist(data$occurrence_day,main="Distribution of Accidents throughout the time",xlab="Days",breaks='months')
```

```{r, include=FALSE}
Time_Occurence_publication=data$publication_day-data$occurrence_day
Time_Occurence_publication=as.numeric(Time_Occurence_publication, units="days")
```

```{r,echo=FALSE}
hist(Time_Occurence_publication)
```

